import subprocess

subprocess.run(['python', 'LP_dam_control1.py'])
# subprocess.run(['python', 'LP_dam_control2.py'])
# subprocess.run(['python', 'LP_dam_control3.py'])
# subprocess.run(['python', 'LP_dam_control4.py'])
# subprocess.run(['python', 'LP_dam_control5.py'])
# subprocess.run(['python', 'LP_dam_control6.py'])
# subprocess.run(['python', 'LP_dam_control7.py'])
# subprocess.run(['python', 'LP_dam_control8.py'])
# subprocess.run(['python', 'LP_dam_control9.py'])
# subprocess.run(['python', 'LP_dam_control10.py'])
# subprocess.run(['python', 'LP_dam_control11.py'])
# subprocess.run(['python', 'LP_dam_control12.py'])
# subprocess.run(['python', 'LP_dam_control13.py'])
# subprocess.run(['python', 'LP_dam_control14.py'])
# subprocess.run(['python', 'LP_dam_control15.py'])
# subprocess.run(['python', 'LP_dam_control16.py'])